---
title: "20250508_regional_association_plots"
output: html_document
date: "2025-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(ggrepel)
library(locuszoomr)
library(EnsDb.Hsapiens.v86)
source("./20250508_locus_ggplot_source.R")
source("./20250508_ggscatter_source.R")
```

```{r}
create_RegAsso_dataframe <- function(chr, batch, group, metab){
  snpinfo <- readRDS(paste0("/Volumes/Sofer Lab/HCHS_SOL/Projects/2023_local_ancestry_comparison_sol/Data/FLARE3/FLARE3_SNPs_filtered_chr", chr,".rds"))
  res <- readRDS(paste0("../Data/STAAR_", group, "/", metab,
                                    "/admixmap_", batch, "_",  metab, 
                                    "_no_genotype.RDS"))
  print(paste0("../Data/STAAR_", group, "/", metab,
                                    "/admixmap_", batch, "_",  metab, 
                                    "_no_genotype.RDS"))
  
  res$Score.pval <- as.numeric(res$Score.pval)
  df <- cbind(rep(chr, nrow(res)), res$snppos,
              snpinfo$rsID[snpinfo$snppos == res$snppos], res$Score.pval,
              res$Est)
  colnames(df) <- c("chrom", "pos", "rsID",
                    "p", "Effect_size")
  df <- as.data.frame(df)
  df$p <- as.numeric(df$p)
  df$pos <- as.numeric(df$pos)
  df$chrom <- as.numeric(df$chrom)
  return(df)
}
```


```{r}
create_RegAssoPlot <- function(df, known_loci,
                               hightlight_genes = NULL,
                               fig_title = "", ylim_max = 20,
                               flanking_l = 500000,
                               flanking_r = 500000){
  
  df$pos <- as.integer(df$pos)
  rownames(df) <- df$rsID
  
  rsid <- c(rownames(df)[which(df$p == min(df$p))[1]])
  
  custom_label <- data.frame(
  x = 0.6,               
  y = 0.9,                 
  label = rsid   
  )

  loc <- locus(df, ens_db = "EnsDb.Hsapiens.v86",
      chrom = "chrom",
      pos = "pos", 
      p = "p",
      labs = "rsID",
      flank = c(flanking_l, flanking_r),
      index_snp = rsid)

  print(loc)
  loc <- link_recomb(loc, genome = loc$genome, table = NULL, recomb = NULL)

locus_ggplot(loc, known_loci, 
               scheme = c('grey', 'dodgerblue', 'red'),
               highlight = hightlight_genes,
               highlight_col = "orange",
               pcutoff = 2.58 * 10^(-6),
               ylim = c(0, ylim_max)
               ) +
    geom_text_repel(data = custom_label, aes(x = x, y = y, label = label), 
                    size = 3, 
                    color = "black",
                    nudge_x = 0.005,
                    nudge_y = 0) +
    
    labs(title = fig_title) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 12, face = "bold")
    )

}
```

```{r}
regasso_df_chr2 <- create_RegAsso_dataframe(2, "b1", "neg_controls", "x100001721")
known_loci_chr2 <- as.data.frame(readRDS("../Data/STAAR_neg_controls/x100001721/individual_cond_pruned_var.RDS"))
create_RegAssoPlot(regasso_df_chr2, as.data.frame(known_loci_chr2), 
                   hightlight_genes = c("EGR4", "ALMS1","FBXO41", "STAMBP", "NAT8",
                                        "TPRKB", "DUSP11"),
                  flanking_l = 1700000, flanking_r = 500000)
```


```{r}
regasso_df_chr5 <- create_RegAsso_dataframe(5, "b1", "neg_controls", "x799")
known_loci_chr5 <- as.data.frame(readRDS("../Data/STAAR_neg_controls/x799/individual_cond_pruned_var.RDS"))

create_RegAssoPlot(regasso_df_chr5, as.data.frame(known_loci_chr5), ylim_max = 15 )
```
```{r}
regasso_df_chr6 <- create_RegAsso_dataframe(6, "b1", "neg_controls", "x1215")
known_loci_chr6 <- as.data.frame(readRDS("../Data/STAAR_neg_controls/x1215/individual_cond_pruned_var.RDS"))

create_RegAssoPlot(regasso_df_chr6, as.data.frame(known_loci_chr6), ylim_max = 15,
                   hightlight_genes = c("UNC93A"))
```
```{r}
regasso_df_chr16 <- create_RegAsso_dataframe(16, "b1", "neg_controls", "x278")
known_loci_chr16 <- as.data.frame(readRDS("../Data/STAAR_neg_controls/x278/individual_cond_pruned_var.RDS"))
create_RegAssoPlot(regasso_df_chr16, as.data.frame(known_loci_chr16),
                   ylim_max = 12,
                   flanking_r = 1500000,
                   flanking_l = 260000)
```



```{r}
regasso_df_chr8 <- create_RegAsso_dataframe(8, "b1", "exp_groups", "x1021")
known_loci_chr8 <- as.data.frame(readRDS("../Data/STAAR_exp_groups/x1021/individual_cond_pruned_var.RDS"))
create_RegAssoPlot(regasso_df_chr8, as.data.frame(known_loci_chr8[-c(1,2), ]),
                   ylim_max = 30, hightlight_genes = c("TSTA3", "JRK", "MAPK15",
                                                       "PLEC", "RHPN1", "EPPK1",
                                                       "NRBP2", "GLI4", "ZNF623",
                                                       "TOP1MT", "NAPRT", "GSDMD",
                                                       "PSCA","C8orf31", "RNU6-220P",
                                                       "MROH6","ZNF707", "PARP10"),
                  flanking_l = 1300000, flaking_r = 500000)

```

```{r}
regasso_df_chr10 <- create_RegAsso_dataframe(10, "b1", "exp_groups", "x100000007")
known_loci_chr10 <- as.data.frame(readRDS("../Data/STAAR_exp_groups/x100000007/individual_cond_pruned_var.RDS"))
create_RegAssoPlot(regasso_df_chr10, as.data.frame(known_loci_chr10),
                   ylim_max = 20, flanking_r = 1900000,
                   flanking_l = 750000)
```
```{r}
regasso_df_chr13 <- create_RegAsso_dataframe(13, "b1", "exp_groups", "x100004046")
known_loci_chr13 <- as.data.frame(readRDS("../Data/STAAR_exp_groups/x100004046/individual_cond_pruned_var.RDS"))
create_RegAssoPlot(regasso_df_chr13, as.data.frame(known_loci_chr13),
                   ylim_max = 10)
```
```{r}
regasso_df_chr16_exp <- create_RegAsso_dataframe(16, "b1", "exp_groups", "x1224")
known_loci_chr16_exp <- as.data.frame(readRDS("../Data/STAAR_exp_groups/x1224/individual_cond_pruned_var_direction
        _pruned.RDS"))
create_RegAssoPlot(regasso_df_chr16_exp, as.data.frame(known_loci_chr16_exp),
                   ylim_max = 35, hightlight_genes = c("DPEP1", "CHMP1A"),
                   flanking_r = 250000)
```




